
Objecive: parse output of log when submitting a job to get jobid



def parse_output_for_jobId(log_file_path):
    with open(log_file_path, "r") as file:
        for line in file:
            print(line)






# The Shepherd job ID can be parsed out of the submission log generated by Shepherd. This is emitted to stderr by Shepherd, when submitting a job, and also written to submit.log in the logging directory, which is defined by the SHEPHERD_LOG environment variable (defaulting to the current working directory, if not set). (See shepherd:cli.dummy.submit for exact details on the output to parse.)

# 2020-06-01T13:51:16Z+0100       INFO    Shepherd: dummy 0.0.1 / lib 0.0.1
# 2020-06-01T13:51:16Z+0100       INFO    Logging to /lustre/scratch119/realdata/mdt3/teams/hgi/shepherd-testing/run/chd
# 2020-06-01T13:51:16Z+0100       INFO    Will transfer contents of /lustre/scratch119/realdata/mdt3/teams/hgi/shepherd-testing/run/chd/fofn to /humgen/archive/chd
# 2020-06-01T13:51:16Z+0100       INFO    Will apply metadata from /lustre/scratch119/realdata/mdt3/teams/hgi/shepherd-testing/run/chd/metadata.json to each file
# 2020-06-01T13:51:17Z+0100       INFO    Created new job with ID 1, with up to 3 attempts per task
# 2020-06-01T13:51:17Z+0100       DEBUG   Running: bsub -n "1" -M "1000" -q "normal" -G "hgi-archive" -R "span[hosts=1] select[mem>1000] rusage[mem=1000]" -o "/lustre/scratch119/realdata/mdt3/teams/hgi/shepherd-testing/run/chd/prep.log" -e "/lustre/scratch119/realdata/mdt3/teams/hgi/shepherd-testing/run/chd/prep.log" "/lustre/scratch119/realdata/mdt3/teams/hgi/shepherd-testing/shepherd/shepherd" __prepare 1
# 2020-06-01T13:51:21Z+0100       INFO    Preparation phase submitted with LSF ID 13203
# 2020-06-01T13:51:21Z+0100       DEBUG   Running: bsub -n "4" -M "1000" -q "long" -G "hgi-archive" -R "span[hosts=1] select[mem>1000] rusage[mem=1000]" -o "/lustre/scratch119/realdata/mdt3/teams/hgi/shepherd-testing/run/chd/transfer.%I.log" -e "/lustre/scratch119/realdata/mdt3/teams/hgi/shepherd-testing/run/chd/transfer.%I.log" -J "shepherd_worker[1-10]" "/lustre/scratch119/realdata/mdt3/teams/hgi/shepherd-testing/shepherd/shepherd" __transfer 1
# 2020-06-01T13:51:21Z+0100       INFO    Transfer phase submitted with LSF ID 13204 and 10 workers


